replicaCount: 2

image:
  repository: europe-west9-docker.pkg.dev/gke-devsecops-stack-26/sample-app-repo/sample-app
  tag: "e6338ec9c2be2efd126e1f4e4bc768d538c8c542"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  ENVIRONNEMENT: "staging"
  LOG_LEVEL: "info"