replicaCount: 2

image:
  repository: europe-west9-docker.pkg.dev/gke-devsecops-stack-26/sample-app-repo/sample-app
  tag: "31c318a4e1c4049e8825b775114ccc4ccfba8540"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  ENVIRONNEMENT: "staging"
  LOG_LEVEL: "info"